### PR TITLE
Mnaveau/fix env add robot

### LINKED ISSUE #1: Do not forward the class on any method
I have notice that to create a robot one should go through the bullet environment.
This is not very practical because one need a `env.add_robot()` compatible with any robot constructor which is wrong.
 Hence I would like to send a robot instance to the env and not the opposite.

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."

Fix the try/except on RobotWrappers constructors.
Add a function to simply add a constructed robot wrapper object.

@jviereck @Lhumd  @huaijiangzhu  @skleff1994 
can you guys make sure that these packages have a PR in order to propagate these changes?
- [x] robot_properties_solo (@MaximilienNaveau  )
- [x] robot_properties_bolt (@Lhumd )
- [x] robot_properties_teststand (@jviereck )
- [x] robot_properties_kuka (@skleff1994 )

## How I Tested

[//]: # "Explain how you tested your changes"

I ran the simulation on the Bolt robot.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Review by jviereck — APPROVED** [review]

**Comment by jviereck** [comment]
> Add a function to simply add a constructed robot wrapper object.

I don't like that there are two ways add robots and would prefer to keep only one way. If you have strong opinions/use cases to add the second one, we can do it.

**Comment by jviereck** [comment]
In general, can you please avoid to do format on PRs together with feature changes? It makes it very hard to figure out what's the actual changes and what are just code formations.

**Comment by MaximilienNaveau** [comment]
> In general, can you please avoid to do format on PRs together with feature changes? It makes it very hard to figure out what's the actual changes and what are just code formations.

This is a 2 commits PR, hence you can just look at the first commit.

**Comment by MaximilienNaveau** [comment]
> > Add a function to simply add a constructed robot wrapper object.
> 
> I don't like that there are two ways add robots and would prefer to keep only one way. If you have strong opinions/use cases to add the second one, we can do it.

Agreed but then we need to refactor a bit the code using this...
Should I just keep the second option then?

**Comment by jviereck** [comment]
> Should I just keep the second option then?

You mean this API? `def add_robot_to_step(self, robot_wrapper_object):`. Works for me, but we would need to refactor all the existing code.

@huaijiangzhu as you wrote the initial code, do you have any input on this?

**Comment by huaijiangzhu** [comment]
The only counterargument I have against constructing a robot wrapper object first and then passing it to the env is: to do that the wrapper has to be constructed after pybullet.connect() is executed, because the wrapper calls pybullet.loadURDF() inside __init__. As such, the user has to make sure that they run pybullet.connect() or create an env object before constructing the robot wrapper. But passing the class and constructing the wrapper object inside the env automatically ensures that. PS. Why do we have naming inconsistency like useFixedBase/use_fixed_base, robot_id/robotId? Should we just chose one naming convention and stick to it?

**Review by Lhumd — APPROVED** [review]

**Comment by MaximilienNaveau** [comment]
> The only counterargument I have against constructing a robot wrapper object first and then passing it to the env is: to do that the wrapper has to be constructed after pybullet.connect() is executed, because the wrapper calls pybullet.loadURDF() inside **init**. As such, the user has to make sure that they run pybullet.connect() or create an env object before constructing the robot wrapper. But passing the class and constructing the wrapper object inside the env automatically ensures that. PS. Why do we have naming inconsistency like useFixedBase/use_fixed_base, robot_id/robotId? Should we just chose one naming convention and stick to it?

In order to prevent that we could had the constructor of the mother class robot_wrapper take the "env" created object?
then the robot could add itself to the environment :thinking:

**Comment by MaximilienNaveau** [comment]
I update the PR removing the formatting so that it is easier to read.

**Comment by huaijiangzhu** [comment]
> > The only counterargument I have against constructing a robot wrapper object first and then passing it to the env is: to do that the wrapper has to be constructed after pybullet.connect() is executed, because the wrapper calls pybullet.loadURDF() inside **init**. As such, the user has to make sure that they run pybullet.connect() or create an env object before constructing the robot wrapper. But passing the class and constructing the wrapper object inside the env automatically ensures that. PS. Why do we have naming inconsistency like useFixedBase/use_fixed_base, robot_id/robotId? Should we just chose one naming convention and stick to it?
> 
> In order to prevent that we could had the constructor of the mother class robot_wrapper take the "env" created object?
> then the robot could add itself to the environment 🤔

That logic can be confusing though. I'd prefer adding the robot wrapper object to the env. I think it's sufficient just to throw out some warning message if pybullet is not connected when constructing the wrapper.

**Comment by MaximilienNaveau** [comment]
> > > The only counterargument I have against constructing a robot wrapper object first and then passing it to the env is: to do that the wrapper has to be constructed after pybullet.connect() is executed, because the wrapper calls pybullet.loadURDF() inside **init**. As such, the user has to make sure that they run pybullet.connect() or create an env object before constructing the robot wrapper. But passing the class and constructing the wrapper object inside the env automatically ensures that. PS. Why do we have naming inconsistency like useFixedBase/use_fixed_base, robot_id/robotId? Should we just chose one naming convention and stick to it?
> > 
> > 
> > In order to prevent that we could had the constructor of the mother class robot_wrapper take the "env" created object?
> > then the robot could add itself to the environment thinking
> 
> That logic can be confusing though. I'd prefer adding the robot wrapper object to the env. I think it's sufficient just to throw out some warning message if pybullet is not connected when constructing the wrapper.

:+1:

**Comment by MaximilienNaveau** [comment]
I will try to add a check/throw in the robot wrapper

**Comment by MaximilienNaveau** [comment]
I tried to find a better way but I failed.
I think we should just document the fact that one need to create an env before a robot wrapper in the readme.
It's actually a design from pybullet not from us so we inherit from this. if document it we should be fine no?
WDYT?

**Comment by MaximilienNaveau** [comment]
@jviereck @Lhumd  @huaijiangzhu  @skleff1994 
can you guys make sure that these packages have a PR in order to propagate these changes?
- [ ] robot_properties_solo (@huaijiangzhu )
- [x] robot_properties_bolt (@Lhumd )
- [x] robot_properties_teststand (@jviereck )
- [ ] robot_properties_kuka (@skleff1994 )

**Comment by jviereck** [comment]
@MaximilienNaveau can it be that you've already updated the robot_properties_teststand code to the new convention? https://github.com/open-dynamic-robot-initiative/robot_properties_teststand/commit/823849dbcdab08c56ff83df29a7b397f09ce1400

**Comment by MaximilienNaveau** [comment]
Yes it might be😅
As well as Bolt
Then @jviereck or @huaijiangzhu can you check Solo?

**Comment by huaijiangzhu** [comment]
> I tried to find a better way but I failed.
> I think we should just document the fact that one need to create an env before a robot wrapper in the readme.
> It's actually a design from pybullet not from us so we inherit from this. if document it we should be fine no?
> WDYT?

that's okay with me!

**Comment by MaximilienNaveau** [comment]
alright let's merge!

**Pull request merged**
